language: python

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
            - sourceline: 'ppa:nicolasbock/qmmd'
        packages:
            - cmake
            - cmake-data
            - g++-6
            - gcc-6
            - gfortran-6
            - libblas-dev
            - libbml-dev
            - liblapack-dev
            - python
            - python3-numpy
            - python-numpy

env:
    - CC=gcc-6 FC=gfortran-6 CXX=g++-6 PROGRESS_OPENMP=yes COMMAND=install

script:
    -  VERBOSE_MAKEFILE=yes EXTRA_LINK_FLAGS="-llapack -lblas" PROGRESS_TESTING=yes CMAKE_BUILD_TYPE=Debug PROGRESS_EXAMPLES=yes ./build.sh ${COMMAND}
    -  cd examples/gpmd; ./run_test.sh
